name: Check FTP

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: npm install basic-ftp
      - name: List FTP Root
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          
          cat << EOF > lftp-script.txt
          set ftp:ssl-allow true
          set ssl:verify-certificate no
          set ftp:passive-mode true
          open -u $FTP_USER,$FTP_PASS $FTP_HOST
          
          echo "==== ls root ===="
          ls
          
          echo "==== ls public_html ===="
          ls public_html
          
          echo "==== ls domains ===="
          ls domains
          
          echo "==== ls domains/aviperera.com ===="
          ls domains/aviperera.com
          
          echo "==== ls domains/aviperera.com/public_html ===="
          ls domains/aviperera.com/public_html
          
          echo "==== DONE ===="
          quit
          EOF
          
          lftp -f lftp-script.txt
