name: Check FTP

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: npm install basic-ftp
      - name: List FTP Root
        env:
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          
          cat << EOF > lftp-script.txt
          set ftp:ssl-allow true
          set ssl:verify-certificate no
          set ftp:passive-mode true
          open -u $FTP_USER,$FTP_PASS 157.173.209.31
          
          echo "==== ls root ===="
          ls -la
          
          echo "==== DONE ===="
          quit
          EOF
          
          lftp -f lftp-script.txt
